# Generated by Django 6.0.7 on 2026-07-24 16:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GastoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "monto_estimado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("dia_vencimiento", models.IntegerField(default=1)),
                (
                    "responsable",
                    models.CharField(
                        choices=[
                            ("COMPARTIDO", "Ambos"),
                            ("ULI", "Uli"),
                            ("EMI", "Emi"),
                        ],
                        default="COMPARTIDO",
                        max_length=15,
                    ),
                ),
                ("es_cuota", models.BooleanField(default=False)),
                (
                    "cuotas_totales",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "cuotas_restantes",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "fecha_fin_cuota",
                    models.DateField(
                        blank=True,
                        help_text="Fecha o mes de finalización de la cuota",
                        null=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Gasto Fijo",
                "verbose_name_plural": "Gastos Fijos",
                "ordering": ["dia_vencimiento"],
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color_hex", models.CharField(default="#ec4899", max_length=7)),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "tipo_division",
                    models.CharField(
                        choices=[
                            ("50_50", "Ambos"),
                            ("EMI", "Emi"),
                            ("ULI", "Uli"),
                            ("EXACT", "Montos Exactos"),
                        ],
                        default="50_50",
                        max_length=10,
                    ),
                ),
                (
                    "monto_emi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monto_uli",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "porcentaje_emi",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "es_tarjeta",
                    models.BooleanField(
                        default=False, verbose_name="Pagado con Tarjeta"
                    ),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "pagado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos_pagados",
                        to="finanzas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
    ]
