# Generated by Django 6.0.7 on 2026-07-24 13:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("icono", models.CharField(default="📦", max_length=10)),
                ("color", models.CharField(default="#94a3b8", max_length=7)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("color_hex", models.CharField(default="#ec4899", max_length=7)),
            ],
            options={
                "verbose_name": "Persona",
                "verbose_name_plural": "Personas",
            },
        ),
        migrations.CreateModel(
            name="GastoFijo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "monto_estimado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("ARS", "Pesos ($ ARS)"),
                            ("USD", "Dólares (US$ USD)"),
                        ],
                        default="ARS",
                        max_length=3,
                    ),
                ),
                ("dia_vencimiento", models.IntegerField(default=10)),
                (
                    "responsable",
                    models.CharField(
                        choices=[
                            ("EMI", "Emi"),
                            ("ULI", "Uli"),
                            ("COMPARTIDO", "Compartido (50/50)"),
                        ],
                        default="COMPARTIDO",
                        max_length=15,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("notas", models.TextField(blank=True, default="")),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="finanzas.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto Fijo",
                "verbose_name_plural": "Gastos Fijos",
                "ordering": ["dia_vencimiento"],
            },
        ),
        migrations.CreateModel(
            name="PagoSaldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("ARS", "Pesos ($ ARS)"),
                            ("USD", "Dólares (US$ USD)"),
                        ],
                        default="ARS",
                        max_length=3,
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("notas", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "pagador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_realizados",
                        to="finanzas.persona",
                    ),
                ),
                (
                    "receptor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos_recibidos",
                        to="finanzas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Saldo",
                "verbose_name_plural": "Pagos de Saldo",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Ingreso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("ARS", "Pesos ($ ARS)"),
                            ("USD", "Dólares (US$ USD)"),
                        ],
                        default="ARS",
                        max_length=3,
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingresos",
                        to="finanzas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingreso",
                "verbose_name_plural": "Ingresos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "moneda",
                    models.CharField(
                        choices=[
                            ("ARS", "Pesos ($ ARS)"),
                            ("USD", "Dólares (US$ USD)"),
                        ],
                        default="ARS",
                        max_length=3,
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "tipo_division",
                    models.CharField(
                        choices=[
                            ("50_50", "Mitad y Mitad (50 / 50)"),
                            ("EXACT", "Montos Exactos por Persona"),
                            ("PERCENT", "Porcentaje Personalizado"),
                            ("FOR_OTHER", "100% Pagado para la Otra Persona"),
                            ("PERSONAL", "100% Personal (No se comparte)"),
                        ],
                        default="50_50",
                        max_length=10,
                    ),
                ),
                (
                    "monto_emi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monto_uli",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "porcentaje_emi",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
                ),
                (
                    "monto_pagado_emi",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monto_pagado_uli",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notas", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gastos",
                        to="finanzas.categoria",
                    ),
                ),
                (
                    "pagado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gastos_pagados",
                        to="finanzas.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gasto",
                "verbose_name_plural": "Gastos",
                "ordering": ["-fecha", "-creado_en"],
            },
        ),
    ]
