# Generated by Django 6.0.7 on 2026-07-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagosaldo",
            name="pagador",
        ),
        migrations.RemoveField(
            model_name="pagosaldo",
            name="receptor",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="moneda",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="monto_pagado_emi",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="monto_pagado_uli",
        ),
        migrations.RemoveField(
            model_name="gastofijo",
            name="moneda",
        ),
        migrations.AddField(
            model_name="gastofijo",
            name="cuotas_restantes",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="gastofijo",
            name="cuotas_totales",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="gastofijo",
            name="es_cuota",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="pagado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gastos_pagados",
                to="finanzas.persona",
            ),
        ),
        migrations.AlterField(
            model_name="gasto",
            name="tipo_division",
            field=models.CharField(
                choices=[
                    ("50_50", "Mitad y Mitad (50 / 50)"),
                    ("EXACT", "Montos Exactos"),
                    ("PERCENT", "Porcentaje Personalizado"),
                ],
                default="50_50",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="Ingreso",
        ),
        migrations.DeleteModel(
            name="PagoSaldo",
        ),
    ]
