# Generated by Django 6.0.7 on 2026-07-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="moneda",
            field=models.CharField(blank=True, default="ARS", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="gastofijo",
            name="moneda",
            field=models.CharField(blank=True, default="ARS", max_length=10, null=True),
        ),
    ]
