# Generated by Django 6.0.7 on 2026-07-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finanzas",
            "0002_remove_pagosaldo_pagador_remove_pagosaldo_receptor_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gastofijo",
            name="fecha_fin_cuota",
            field=models.DateField(
                blank=True,
                help_text="Fecha o mes de finalización de la cuota",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="gastofijo",
            name="dia_vencimiento",
            field=models.IntegerField(default=1),
        ),
    ]
