# Generated by Django 6.0.7 on 2026-07-24 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0002_gasto_moneda_gastofijo_moneda"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Varios", max_length=50)),
                ("icono", models.CharField(default="📦", max_length=10)),
                ("color", models.CharField(default="#94a3b8", max_length=7)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AddField(
            model_name="gasto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finanzas.categoria",
            ),
        ),
        migrations.AddField(
            model_name="gastofijo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finanzas.categoria",
            ),
        ),
    ]
