# Generated by Django 6.0.7 on 2026-07-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_gastofijo_fecha_fin_cuota_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gastofijo",
            name="categoria",
        ),
        migrations.RemoveField(
            model_name="gasto",
            name="categoria",
        ),
        migrations.AlterField(
            model_name="gasto",
            name="tipo_division",
            field=models.CharField(
                choices=[
                    ("50_50", "Ambos (Mitad y Mitad 50/50)"),
                    ("EMI", "Propios de Emi (100% Emi)"),
                    ("ULI", "Propios de Uli (100% Uli)"),
                    ("EXACT", "Montos Exactos"),
                    ("PERCENT", "Porcentaje Personalizado"),
                ],
                default="50_50",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gastofijo",
            name="responsable",
            field=models.CharField(
                choices=[
                    ("COMPARTIDO", "Ambos (50/50)"),
                    ("ULI", "Uli"),
                    ("EMI", "Emi"),
                ],
                default="COMPARTIDO",
                max_length=15,
            ),
        ),
        migrations.DeleteModel(
            name="Categoria",
        ),
    ]
