# Generated by Django 6.0.7 on 2026-07-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_categoria_gasto_categoria_gastofijo_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="monto_pagado_emi",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="gasto",
            name="monto_pagado_uli",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
    ]
