# Generated by Django 6.0.7 on 2026-07-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0004_remove_gastofijo_categoria_remove_gasto_categoria_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gasto",
            name="tipo_division",
            field=models.CharField(
                choices=[
                    ("50_50", "Ambos"),
                    ("EMI", "Emi"),
                    ("ULI", "Uli"),
                    ("EXACT", "Montos Exactos"),
                ],
                default="50_50",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="gastofijo",
            name="responsable",
            field=models.CharField(
                choices=[("COMPARTIDO", "Ambos"), ("ULI", "Uli"), ("EMI", "Emi")],
                default="COMPARTIDO",
                max_length=15,
            ),
        ),
    ]
