# Generated by Django 6.0.7 on 2026-07-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0005_alter_gasto_tipo_division_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="es_tarjeta",
            field=models.BooleanField(default=False, verbose_name="Pagado con Tarjeta"),
        ),
    ]
